import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {
  formatUserText,
  extractLastAssistantText,
  extractNonFinalAssistantTexts,
  extractToolUses,
  extractToolResults,
  formatToolUseSummary,
  formatToolResultSummary,
  toBlocks,
} from './contentFormatter.js';
import { renderTemplate, templateHasCcxlogIdMarker } from './templates.js';
import {
  extractModel,
  extractVersion,
  extractGitBranch,
  extractCwd,
  extractTokenTotals,
  formatTokens,
} from './metaExtractor.js';
import { encodeSid64, chooseMethod, regionFromLine } from './identity.js';
import { sha256Hex } from './pathUtils.js';
import type {
  Pair, UserEntry, AssistantEntry, ContentBlock, Source, SourceLabel, SourceMode, UnifiedPair,
} from './types.js';

const NOTICE = '<!-- Generated by ccxlog. Do not edit (regenerated on each run). -->';
const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function pad2(n: number): string { return n < 10 ? '0' + n : '' + n; }

function sanitizeRawTimestamp(raw: string): string {
  return raw
    .replace(/[\r\n]+/g, ' ')
    // Strip C0 + NUL (<=0x1f), DEL (0x7f) and C1 controls (0x80-0x9f) so the
    // rule matches config.hasControlOrNul (§8.3 / §4.3 consistency).
    .split('').filter(ch => {
      const c = ch.charCodeAt(0);
      return c > 0x1f && c !== 0x7f && !(c >= 0x80 && c <= 0x9f);
    }).join('')
    .replaceAll('-->', '-- >').replaceAll('<!--', '<! --');
}

// %DateTime% with the §8.3 unique rule for unparseable timestamps.
export function formatDateTime(u: Pick<UnifiedPair, 'questionTimestampMs' | 'questionTimestampRaw'>): string {
  if (u.questionTimestampMs !== null) {
    const d = new Date(u.questionTimestampMs);
    return `${d.getFullYear()}/${pad2(d.getMonth() + 1)}/${pad2(d.getDate())} `
      + `${WEEKDAYS[d.getDay()]} ${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
  }
  if (u.questionTimestampRaw !== '') return sanitizeRawTimestamp(u.questionTimestampRaw);
  return 'Unknown';
}

// ---- progress rendering (ported from cclog) ------------------------------

function oneLine(s: string): string {
  const stripped = s.replace(/\s+/g, ' ').trim();
  return stripped.length > 200 ? stripped.slice(0, 200) + '...' : stripped;
}

function progressLinesFor(entry: UserEntry | AssistantEntry, includeFull: boolean): string[] {
  const lines: string[] = [];
  const content = entry.message?.content;
  if (content === undefined || content === null) return lines;

  if (entry.type === 'user') {
    for (const tr of extractToolResults(content)) {
      lines.push(`- ${formatToolResultSummary(tr, includeFull)}`);
    }
    return lines;
  }

  const blocks: ContentBlock[] = toBlocks(content);
  for (const b of blocks) {
    if (b.type === 'text' && typeof (b as { text?: unknown }).text === 'string') {
      const line = oneLine((b as { text: string }).text);
      if (line) lines.push(`- (assistant) ${line}`);
    } else if (b.type === 'tool_use') {
      lines.push(`- ${formatToolUseSummary(b, includeFull)}`);
    } else if (b.type === 'tool_result') {
      lines.push(`- ${formatToolResultSummary(b, includeFull)}`);
    } else if (b.type === 'image') {
      lines.push('- [Image]');
    } else if (b.type === 'thinking') {
      if (includeFull) {
        const t = (b as { thinking?: unknown }).thinking;
        lines.push(`- [Thinking] ${oneLine(typeof t === 'string' ? t : '')}`);
      }
    } else {
      lines.push(`- [${b.type}]`);
    }
  }
  return lines;
}

function buildProgress(pair: Pair, includeFull: boolean): string {
  const lines: string[] = [];
  for (const entry of pair.progressEntries) {
    lines.push(...progressLinesFor(entry, includeFull));
  }
  if (pair.finalAssistantEntry) {
    const fa = pair.finalAssistantEntry;
    for (const t of extractNonFinalAssistantTexts(fa.message.content)) {
      const line = oneLine(t);
      if (line) lines.push(`- (assistant) ${line}`);
    }
    for (const tu of extractToolUses(fa.message.content)) {
      lines.push(`- ${formatToolUseSummary(tu, includeFull)}`);
    }
  }
  return lines.join('\n');
}

function buildQuestion(pair: Pair): string {
  const qParts: string[] = [formatUserText(pair.questionEntry.message.content)];
  for (const extra of pair.additionalQuestionEntries) {
    const t = formatUserText(extra.message.content);
    if (t) qParts.push(t);
  }
  return qParts.filter(Boolean).join('\n\n');
}

function buildAnswer(pair: Pair): string {
  let answerText = '';
  if (pair.finalAssistantEntry) {
    answerText = extractLastAssistantText(pair.finalAssistantEntry.message.content) ?? '';
  }
  if (!answerText) {
    for (let i = pair.progressEntries.length - 1; i >= 0; i--) {
      const entry = pair.progressEntries[i];
      if (entry.type !== 'assistant') continue;
      // Progress-only entries (reasoning / tool activity / developer messages)
      // are never the final answer — skip them so an interrupted turn does not
      // promote e.g. a "[Developer] …" message into %Answer% (§6.2).
      if (entry.isProgressOnly) continue;
      const t = extractLastAssistantText(entry.message.content);
      if (t) { answerText = t; break; }
    }
  }
  return answerText;
}

export interface UnifyParams {
  pair: Pair;
  source: Source;
  sourceLabel: SourceLabel;
  sessionId: string;
  sessionName: string;
  sourceFile: string;
  sourceFileRelativeId: string;
  fileContentHash: string;
  eventIdStreamHash: string[];
  questionOrdinal: number;
}

export function toUnifiedPair(p: UnifyParams): UnifiedPair {
  const { pair } = p;
  const raw = pair.questionEntry.timestamp ?? '';
  const ms = raw ? Date.parse(raw) : NaN;
  // Cross-session dedupe keys (§6.3). Real Claude message UUIDs are globally
  // unique, so a uuid shared across sessions marks a resumed/forked copy of the
  // same turn. We collect the question uuid, the steering follow-up uuids, and
  // the answer uuid — the answer matters because a session-specific extra
  // message can regroup the same shared turn so the question side looks
  // different while the answer is the very same message. Codex uuids are
  // per-file positional (u-0, a-1, …), NOT stable across sessions, so they are
  // deliberately excluded (empty for every Codex pair).
  const forkKeys: string[] = [];
  if (p.source === 'claude') {
    if (pair.questionEntry.uuid) forkKeys.push(pair.questionEntry.uuid);
    for (const q of pair.additionalQuestionEntries) if (q.uuid) forkKeys.push(q.uuid);
    if (pair.finalAssistantEntry?.uuid) forkKeys.push(pair.finalAssistantEntry.uuid);
  }
  return {
    source: p.source,
    sourceLabel: p.sourceLabel,
    sessionId: p.sessionId,
    sessionName: p.sessionName,
    sourceFile: p.sourceFile,
    sourceFileRelativeId: p.sourceFileRelativeId,
    questionEventUuid: pair.questionEntry.uuid || undefined,
    questionOrdinal: p.questionOrdinal,
    questionTimestampRaw: raw,
    questionTimestampMs: Number.isNaN(ms) ? null : ms,
    question: buildQuestion(pair),
    progressSummary: buildProgress(pair, false),
    progressFull: buildProgress(pair, true),
    answer: buildAnswer(pair),
    model: extractModel(pair),
    version: extractVersion(pair),
    gitBranch: extractGitBranch(pair),
    cwd: extractCwd(pair),
    tokens: extractTokenTotals(pair, p.source),
    ccxid: '',
    fileContentHash: p.fileContentHash,
    eventIdStreamHash: p.eventIdStreamHash,
    forkKeys,
  };
}

export function formatPair(u: UnifiedPair, template: string): string {
  const rendered = renderTemplate(template, {
    DateTime: formatDateTime(u),
    Source: u.sourceLabel,
    SourceShort: u.source === 'claude' ? 'cc' : 'cx',
    CcxlogId: u.ccxid,
    SessionId: u.sessionId,
    SessionName: u.sessionName,
    Question: u.question,
    Progress: u.progressSummary,
    ProgressFull: u.progressFull,
    Answer: u.answer,
    Model: u.model,
    Version: u.version,
    GitBranch: u.gitBranch,
    Cwd: u.cwd,
    Tokens: formatTokens(u.tokens),
  });
  if (templateHasCcxlogIdMarker(template)) return rendered;
  return `<!-- ${u.ccxid} -->\n${rendered}`;
}

// ---- preambles -----------------------------------------------------------

export function buildAggregatePreamble(
  mode: SourceMode,
  projectPath: string,
  fileName: string,
  sourceLabels: string[],
): string {
  const base = path.basename(fileName, path.extname(fileName)) || 'ccxlog';
  const owner = `<!-- ccxlog-owner:ccxlog; kind:aggregate; mode:${mode} -->`;
  return [
    owner,
    NOTICE,
    `# ${base}`,
    '',
    `- Project: ${projectPath}`,
    `- Source: ${sourceLabels.join(', ')}`,
    '',
    '',
  ].join('\n');
}

export function buildSessionPreamble(
  source: Source,
  sourceLabel: SourceLabel,
  sessionId: string,
  jsonlPath: string,
  projectPath: string,
): string {
  const owner = `<!-- ccxlog-owner:ccxlog; kind:session; source:${source}; sid64:${encodeSid64(sessionId)} -->`;
  return [
    owner,
    NOTICE,
    `# CCXLog: [${sourceLabel}] ${sessionId}`,
    '',
    `- Project: ${projectPath}`,
    `- Source: ${jsonlPath}`,
    '',
    '',
  ].join('\n');
}

// ---- ownership -----------------------------------------------------------

const AGG_OWNER_RE = /^<!-- ccxlog-owner:ccxlog; kind:aggregate; mode:(both|claude|codex) -->$/;
const SESSION_OWNER_RE = /^<!-- ccxlog-owner:ccxlog; kind:session; source:(claude|codex); sid64:([A-Za-z0-9_-]+) -->$/;
const LEGACY_AGG = /^# (ccxlog|cclog|cxlog)\s*$/;
const LEGACY_SESSION = /^# (CCXLog|CCLog|CXLog):/;

export type Ownership = 'owned' | 'unconfirmed';

export function checkAggregateOwnership(existing: string): Ownership {
  const lines = existing.split('\n', 8);
  if (AGG_OWNER_RE.test(lines[0] ?? '')) return 'owned';
  for (const line of lines) {
    if (LEGACY_AGG.test(line)) return 'owned';
  }
  return 'unconfirmed';
}

export function checkSessionOwnership(existing: string): Ownership {
  const lines = existing.split('\n', 8);
  if (SESSION_OWNER_RE.test(lines[0] ?? '')) return 'owned';
  for (const line of lines) {
    if (LEGACY_SESSION.test(line)) return 'owned';
  }
  return 'unconfirmed';
}

function ownerMarkerLine(content: string): string {
  const nl = content.indexOf('\n');
  return nl === -1 ? content : content.slice(0, nl);
}

// ---- atomic write --------------------------------------------------------

function randomToken(): string {
  return crypto.randomBytes(8).toString('hex');
}

async function atomicWrite(filePath: string, content: string): Promise<void> {
  const dir = path.dirname(filePath);
  const tmp = path.join(dir, `.ccxlog.tmp-${process.pid}-${randomToken()}`);
  const fh = await fs.open(tmp, 'wx');
  try {
    await fh.writeFile(content, 'utf-8');
    await fh.sync();
  } finally {
    await fh.close();
  }
  const transientCodes = new Set(['EPERM', 'EACCES', 'EBUSY']);
  let lastErr: unknown;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      await fs.rename(tmp, filePath);
      return;
    } catch (e: unknown) {
      lastErr = e;
      const code = (e as NodeJS.ErrnoException).code ?? '';
      if (!transientCodes.has(code)) break;
      await new Promise(r => setTimeout(r, 20 * (attempt + 1)));
    }
  }
  await fs.rm(tmp, { force: true });
  throw lastErr;
}

export type WriteResult = 'create' | 'noop' | 'append' | 'rewrite';

// ---- write planning + commit (§8.5) --------------------------------------
// The write path is split into a PLAN phase (no FS mutation; records each
// target's size/mtime/hash) and a COMMIT phase. Callers take every required
// backup and verify them BEFORE any commit, then commit each file with a
// just-before-write re-check that re-plans once and stops on the safe side
// if the file changed again (§8.5 steps 2-4).

export interface FileFingerprint { size: number; mtimeMs: number; contentHash: string; }

// The fingerprint content hash is a FULL-file SHA-256 (not a head/tail sample):
// the whole point of the hash is to catch a same-size / same-mtime in-place
// edit, and a head+tail hash is blind to a middle-only edit (a limitation both
// r3 reports flagged). Only the few output Markdown files are hashed here —
// never the large input JSONL — so §12.3's stream-reading budget is unaffected.
export function contentHashOf(content: string): string {
  return sha256Hex(content);
}

export interface WritePlan {
  filePath: string;
  kind: 'aggregate' | 'session';
  newContent: string;
  outcome: WriteResult;
  backupRequired: boolean;              // true for every rewrite of an existing file
  appendTail: string;                   // only meaningful for 'append'
  fingerprint: FileFingerprint | null;  // existing file at plan time (null if absent)
}

export type PlanResult = { ok: true; plan: WritePlan } | { ok: false; error: string };

// Read the existing file through a SINGLE file handle so the bytes, size and
// mtime form one consistent snapshot. Taking fs.readFile and fs.stat as two
// separate calls leaves a TOCTOU window where the file changes between them and
// the fingerprint pairs old bytes with a new size/mtime (r4 report #2).
async function readExisting(filePath: string): Promise<{ content: string; fp: FileFingerprint } | null> {
  let fh: Awaited<ReturnType<typeof fs.open>>;
  try {
    fh = await fs.open(filePath, 'r');
  } catch (e: unknown) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw e;
  }
  try {
    const content = await fh.readFile('utf-8');
    const st = await fh.stat();
    return { content, fp: { size: st.size, mtimeMs: st.mtimeMs, contentHash: contentHashOf(content) } };
  } finally {
    await fh.close();
  }
}

// Decide the write outcome without mutating the filesystem (§8.5 plan phase).
// An ownership-unconfirmed existing file is a fatal error (no auto-overwrite).
export async function planWrite(
  filePath: string,
  newContent: string,
  kind: 'aggregate' | 'session',
): Promise<PlanResult> {
  const ex = await readExisting(filePath);
  if (!ex) {
    return { ok: true, plan: { filePath, kind, newContent, outcome: 'create', backupRequired: false, appendTail: '', fingerprint: null } };
  }
  const ownership = kind === 'aggregate' ? checkAggregateOwnership(ex.content) : checkSessionOwnership(ex.content);
  if (ownership === 'unconfirmed') {
    return {
      ok: false,
      error: `Refusing to overwrite ownership-unconfirmed file: ${filePath}. `
        + `Move it aside or set a different output name.`,
    };
  }
  const { oldFirstLine, newFirstLine } = chooseMethod(ex.content, newContent);
  const oldRegion = regionFromLine(ex.content, oldFirstLine);
  const newRegion = regionFromLine(newContent, newFirstLine);
  const oldOwner = ownerMarkerLine(ex.content);
  const newOwner = ownerMarkerLine(newContent);
  const oldOwnerIsMarker = AGG_OWNER_RE.test(oldOwner) || SESSION_OWNER_RE.test(oldOwner);
  const newOwnerIsMarker = AGG_OWNER_RE.test(newOwner) || SESSION_OWNER_RE.test(newOwner);
  const ownerMatches = oldOwnerIsMarker && newOwnerIsMarker && oldOwner === newOwner;

  let outcome: WriteResult;
  let appendTail = '';
  if (!ownerMatches) {
    outcome = 'rewrite';                       // fixed management part mismatch (§8.1)
  } else if (oldRegion === newRegion) {
    outcome = 'noop';
  } else if (newRegion.startsWith(oldRegion)) {
    outcome = 'append';
    appendTail = newRegion.slice(oldRegion.length);
  } else {
    outcome = 'rewrite';
  }
  const backupRequired = outcome === 'rewrite';
  return { ok: true, plan: { filePath, kind, newContent, outcome, backupRequired, appendTail, fingerprint: ex.fp } };
}

// Re-check against the plan-time fingerprint (§8.5 step 4). True = the file
// changed under us since planning. Reads size, mtime and the bytes through a
// SINGLE file handle (one consistent snapshot, no read/stat TOCTOU) and
// compares size, mtime AND a full-content SHA-256, so even a same-size /
// same-mtime in-place edit that only touches the MIDDLE of the file is detected.
export async function fingerprintChanged(filePath: string, fp: FileFingerprint | null): Promise<boolean> {
  let fh: Awaited<ReturnType<typeof fs.open>>;
  try {
    fh = await fs.open(filePath, 'r');
  } catch (e: unknown) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') return fp !== null; // planned-existing vanished
    throw e;
  }
  try {
    if (fp === null) return true; // planned as create, but a file now exists
    const content = await fh.readFile('utf-8');
    const st = await fh.stat();
    return st.size !== fp.size || st.mtimeMs !== fp.mtimeMs || contentHashOf(content) !== fp.contentHash;
  } finally {
    await fh.close();
  }
}

// Copy filePath into backupDir and verify (exists + size + SHA-256) (§8.5
// step 3). Returns whether the backup is verified.
export async function backupAndVerify(filePath: string, backupDir: string): Promise<boolean> {
  try {
    await fs.mkdir(backupDir, { recursive: true });
    const dest = path.join(backupDir, path.basename(filePath));
    await fs.copyFile(filePath, dest);
    const [srcBuf, dstBuf] = await Promise.all([fs.readFile(filePath), fs.readFile(dest)]);
    return srcBuf.length === dstBuf.length && sha256Hex(srcBuf) === sha256Hex(dstBuf);
  } catch {
    return false;
  }
}

export interface CommitOptions {
  dryRun: boolean;
  alreadyBackedUp: boolean;   // this file's backup was taken+verified in the batch phase
  backupDir?: string;         // for a just-in-time backup if a re-plan becomes a rewrite
}

export interface CommitResult { result: WriteResult; error?: string; }

async function performWrite(plan: WritePlan): Promise<CommitResult> {
  if (plan.outcome === 'noop') return { result: 'noop' };
  if (plan.outcome === 'append') {
    await fs.appendFile(plan.filePath, plan.appendTail, 'utf-8');
    return { result: 'append' };
  }
  await atomicWrite(plan.filePath, plan.newContent); // create | rewrite
  return { result: plan.outcome };
}

// Commit a planned write with a just-before-write re-check (§8.5 step 4). Even
// a planned `noop` is re-checked: if the file changed under us since planning,
// reporting "noop" would be a lie, so we re-plan once and act on the new plan.
export async function commitPlan(plan: WritePlan, opts: CommitOptions): Promise<CommitResult> {
  if (opts.dryRun) return { result: plan.outcome };

  if (!(await fingerprintChanged(plan.filePath, plan.fingerprint))) {
    return performWrite(plan); // unchanged — a real noop touches nothing (§8.5 step 5)
  }

  // The file changed since planning — re-plan exactly once (§8.5).
  const re = await planWrite(plan.filePath, plan.newContent, plan.kind);
  if (!re.ok) return { result: plan.outcome, error: re.error };
  const rp = re.plan;
  if (rp.outcome === 'noop') return { result: 'noop' };
  if (rp.backupRequired && !opts.alreadyBackedUp && opts.backupDir) {
    if (!(await backupAndVerify(rp.filePath, opts.backupDir))) {
      return { result: rp.outcome, error: `Backup failed for ${rp.filePath}; not overwriting.` };
    }
  }
  // A second change means concurrent external writes — stop on the safe side.
  if (await fingerprintChanged(rp.filePath, rp.fingerprint)) {
    return { result: rp.outcome, error: `${rp.filePath} changed again during write; stopping on the safe side (§8.5).` };
  }
  return performWrite(rp);
}
