//
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { ROOT, CLI, mkTmp, rmrf } from './helpers.mjs';
import {
  writeProgressFixture, claudeRecords, codexRecords, TEMPLATES, MODES, AGGREGATE_NAME,
  useTemplate, normalize, SLASH_FULL_BODY, CODEX_ROLLOUT_NAME,
} from './progressFixture.mjs';

function pathToUrl(p) {
  return new URL(`file:///${p.replace(/\\/g, '/')}`).href;
}

const dist = (...p) => pathToUrl(path.join(ROOT, 'dist', ...p));
const { buildPairs: buildClaudePairs } = await import(dist('sources', 'claude', 'pairBuilder.js'));
const { readJsonl: readCodexJsonl } = await import(dist('sources', 'codex', 'jsonlReader.js'));
const { buildPairs: buildCodexPairs } = await import(dist('sources', 'codex', 'pairBuilder.js'));
const { toUnifiedPair, formatPair } = await import(dist('lib', 'markdownWriter.js'));
const { applyProgressRetention, dropProgressData, progressDataNeeded } =
  await import(dist('lib', 'progressData.js'));
const { templateUsesProgress } = await import(dist('lib', 'templates.js'));
const { createAnalysisCache, cacheKey } = await import(dist('lib', 'analysisCache.js'));

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function childEnv(home) {
  return { ...process.env, HOME: home, USERPROFILE: home, HOMEDRIVE: '', HOMEPATH: '', TZ: 'UTC' };
}

function runCliUtc(args, home) {
  const r = spawnSync(process.execPath, [CLI, ...args], { env: childEnv(home), cwd: ROOT, encoding: 'utf-8' });
  return { code: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

function sha256Text(s) {
  return crypto.createHash('sha256').update(s, 'utf-8').digest('hex');
}

function fixtureWorkspace(t) {
  const home = mkTmp('ccx-progress-');
  const project = path.join(home, 'proj');
  const out = path.join(project, 'CCXLOG');
  writeProgressFixture(home, project);
  if (t) t.after(() => { killLiveWatches(); rmrf(home); });
  return { home, project, out };
}

function clearMd(dir) {
  fs.mkdirSync(dir, { recursive: true });
  for (const f of fs.readdirSync(dir)) {
    if (f.endsWith('.md')) fs.rmSync(path.join(dir, f));
  }
}

function renderCombination(ws, tplKey, modeKey) {
  clearMd(ws.out);
  useTemplate(ws.out, tplKey);
  const r = runCliUtc([ws.project, ...MODES[modeKey]], ws.home);
  assert.equal(r.code, 0, `${tplKey}/${modeKey}: ${r.stderr}`);
  const text = fs.readFileSync(path.join(ws.out, AGGREGATE_NAME[modeKey]), 'utf-8');
  return normalize(text, { home: ws.home, project: ws.project });
}

// ---------------------------------------------------------------------------
// P-1: byte-invariance of the output (3 modes x Progress referenced or not)
// ---------------------------------------------------------------------------

const GOLDEN = {
  'none/ccxlog': '48ccd1901d62bc3623ded7acccb0fe32fb9a0cd988680574dfc124e034d60cc2',
  'none/cc': '52179e06fee4df63f7cf15696ab270916aaf7c02a64200072a0f7e2b0cef4e27',
  'none/cx': '88d460ca5af9a9619d455a5d4d53327238fab67bbf9c2df84d1ef20df4405f4f',
  'summary/ccxlog': '48b39ae2b66a1951ff95c6d18c31415697b9c894ff07dfaa3418891f181ca3e4',
  'summary/cc': '4fec6ebe52e8e8aaef31c1542391ee23eb4e190e341df66275cea299bfdd80e8',
  'summary/cx': 'd645f94958a02497bec9e1f8ec6da78a48d2631890f2b7a47c85689b8bca7ac9',
  'full/ccxlog': 'bf55af274f4786b7666c8de2f15b5b8d15e2745145f54529fd1c50de1150f5bf',
  'full/cc': '1faebf346db123f4eb358118586aeced103c734a5746532fde2576e2141b982e',
  'full/cx': 'f17cbde51c417b83c93b9d124dff381040bf811a481d29403b0de3023fc9ce7f',
  'both/ccxlog': '9b2bd003275c1e821734bf7b6e1f8a2fcdcc680f3c5e3a0ee5b00f41e0663517',
  'both/cc': '3713dd35f5c8229387ef4cfb8d0bd0004a199e677f62d789341ef4f43337c391',
  'both/cx': '59d3c3a41eefb8649d22b8bc552998ff205adccd8eca3314afb220bf345160fc',
};

test('P-1: output for three modes and four templates is byte-identical to the baseline', (t) => {
  const ws = fixtureWorkspace(t);
  for (const tplKey of Object.keys(TEMPLATES)) {
    for (const modeKey of Object.keys(MODES)) {
      const norm = renderCombination(ws, tplKey, modeKey);
      assert.equal(sha256Text(norm), GOLDEN[`${tplKey}/${modeKey}`],
        `${tplKey}/${modeKey} output differs from the baseline:\n${norm}`);
    }
  }
});

const GOLDEN_BOTH_CCXLOG = `<!-- ccxlog-owner:ccxlog; kind:aggregate; mode:both -->
<!-- Generated by ccxlog. Do not edit (regenerated on each run). -->
# ccxlog

- Project: <PROJECT>
- Source: ClaudeCode, Codex

<!-- ccxlogid:7f39f2d7ad37f6aa87f68fe2 -->
# 2026/05/27 Wed 11:00:00 [ClaudeCode/cc] :sess1
Model=claude-opus-4-8-inner Version=1.2.3
Branch=main Cwd=<PROJECT>
Tokens=in 15, out 8, cache read 100, cache write 10
## Question
First question
## Answer
Final answer 1.
## Progress
- [ToolResult: output line 0...]
- (assistant) Let me look at the file.
- [Tool: Read C:/x/y.txt]
- [Image]
- (assistant) Intermediate note.
- [Tool: Bash echo done]
## ProgressFull
- [ToolResult] output line 0
output line 1
output line 2
output line 3
output line 4
output line 5
output line 6
output line 7
output line 8
output line 9
output line 10
output line 11
- (assistant) Let me look at the file.
- [Tool: Read] {"file_path":"C:/x/y.txt","limit":100}
- [Thinking] internal reasoning that only ProgressFull shows
- [Image]
- (assistant) Intermediate note.
- [Tool: Bash] {"command":"echo done"}
--------

<!-- ccxlogid:c98429f05050e9896967ef23 -->
# 2026/05/27 Wed 11:10:00 [ClaudeCode/cc] :sess1
Model=claude-sonnet-5 Version=9.9.9
Branch=feature/x Cwd=<PROJECT>
Tokens=
## Question
Second question
## Answer
Partial thought.
## Progress
- (assistant) Partial thought.
- [Tool: Grep needle]
- [Tool: Write C:/x/z.txt]
## ProgressFull
- (assistant) Partial thought.
- [Tool: Grep] {"pattern":"needle"}
- [Tool: Write] {"file_path":"C:/x/z.txt"}
--------

<!-- ccxlogid:7c5499a949ba2038492ab301 -->
# 2026/05/27 Wed 11:20:00 [ClaudeCode/cc] :sess1
Model=claude-opus-4-8 Version=1.2.3
Branch=main Cwd=<PROJECT>
Tokens=in 2, out 2, cache read 0, cache write 0
## Question
<command-name>/mycmd</command-name>

Do the thing.
Step 1
Step 2
Step 3
## Answer
Final answer 3.
## Progress
- [ToolResult: Do the thing....]
- [Tool: Read C:/fixture-home/.claude/commands/mycmd.md]
## ProgressFull
- [ToolResult] Do the thing.
Step 1
Step 2
Step 3
- [Tool: Read] {"file_path":"C:/fixture-home/.claude/commands/mycmd.md"}
--------

<!-- ccxlogid:759014938c4d43eff1b2810e -->
# 2026/05/27 Wed 12:01:00 [Codex/cx] :cx-sess-0001
Model=gpt-5-codex Version=0.9.9
Branch=main Cwd=<PROJECT>
Tokens=in 150, out 45, cache read 20, reasoning 9
## Question
Codex question one
## Answer
Codex answer one.
## Progress
- [Tool: shell ls -la]
- [ToolResult: output line 0...]
## ProgressFull
- [Thinking] codex thinking
- [Tool: shell] {"command":"ls -la"}
- [ToolResult] output line 0
output line 1
output line 2
output line 3
output line 4
output line 5
output line 6
output line 7
output line 8
output line 9
output line 10
output line 11
--------

<!-- ccxlogid:b9d1a3b0b0c86e56c9262ab7 -->
# 2026/05/27 Wed 12:09:00 [Codex/cx] :cx-sess-0001
Model=gpt-5-codex Version=0.9.9
Branch=main Cwd=<PROJECT>
Tokens=
## Question
Codex question two
## Answer

## Progress

## ProgressFull
- [Thinking] interrupted
--------

`;

test('P-2: representative complete outputs match readable baselines', (t) => {
  const ws = fixtureWorkspace(t);
  assert.equal(renderCombination(ws, 'both', 'ccxlog'), GOLDEN_BOTH_CCXLOG);
});

// ---------------------------------------------------------------------------
// P-3: discarding vs keeping changes the rendering by not one byte (unit)
// ---------------------------------------------------------------------------

async function fixturePairs(t) {
  const home = mkTmp('ccx-progress-unit-');
  const project = path.join(home, 'proj');
  if (t) t.after(() => rmrf(home));
  const claude = buildClaudePairs(claudeRecords(project), {});
  const rolloutPath = path.join(home, CODEX_ROLLOUT_NAME);
  fs.writeFileSync(rolloutPath,
    codexRecords(project).map(r => JSON.stringify(r)).join('\n') + '\n', 'utf-8');
  const codex = buildCodexPairs((await readCodexJsonl(rolloutPath)).entries);
  return { claude, codex };
}

function renderPairs(pairs, source, template) {
  return pairs.map((pair, i) => formatPair(toUnifiedPair({
    pair,
    source,
    sourceLabel: source === 'claude' ? 'ClaudeCode' : 'Codex',
    sessionId: 'sess', sessionName: '', sourceFile: '/x.jsonl',
    sourceFileRelativeId: `${source}/standard/std/x.jsonl`,
    fileContentHash: async () => '', eventIdStream: [], questionOrdinal: i,
  }), template)).join('');
}

test('P-3: templates without Progress render identically with retained or discarded data', async (t) => {
  const src = await fixturePairs(t);
  for (const [source, pairs] of Object.entries(src)) {
    const dropped = structuredClone(pairs);
    dropProgressData(dropped);
    assert.equal(
      renderPairs(dropped, source, TEMPLATES.none),
      renderPairs(pairs, source, TEMPLATES.none),
      `${source}: rendering without Progress must not depend on retention`,
    );
  }
});

function isSlim(pairs) {
  return pairs.every(p => p.progressEntries.every(e => {
    const blocks = Array.isArray(e.message?.content) ? e.message.content : [];
    return blocks.every(b => b.type === 'text') && e.uuid === undefined && e.timestamp === undefined;
  }));
}

test('P-3b: templates using Progress retain data and preserve rendering', async (t) => {
  const src = await fixturePairs(t);
  for (const key of ['summary', 'full', 'both']) {
    for (const [source, pairs] of Object.entries(src)) {
      const kept = applyProgressRetention(structuredClone(pairs), { template: TEMPLATES[key] });
      assert.equal(isSlim(kept), false, `${key}/${source}: data must not be discarded`);
      assert.equal(
        renderPairs(kept, source, TEMPLATES[key]),
        renderPairs(pairs, source, TEMPLATES[key]),
        `${key}/${source}: rendering must remain unchanged`,
      );
    }
  }
  for (const [source, pairs] of Object.entries(src)) {
    const dropped = applyProgressRetention(structuredClone(pairs), { template: TEMPLATES.none });
    assert.equal(isSlim(dropped), true, `${source}: unused Progress data must be slimmed`);
  }
});

test('P-3c: discarding data preserves progressEntries count, order, and types', async (t) => {
  const src = await fixturePairs(t);
  for (const [source, pairs] of Object.entries(src)) {
    const dropped = structuredClone(pairs);
    dropProgressData(dropped);
    for (let i = 0; i < pairs.length; i++) {
      assert.deepEqual(
        dropped[i].progressEntries.map(e => e.type),
        pairs[i].progressEntries.map(e => e.type),
        `${source} pair ${i}`,
      );
    }
  }
});

// ---------------------------------------------------------------------------
// P-4: the heavy payloads really are gone (what the memory saving consists of)
// ---------------------------------------------------------------------------

function progressBodyBytes(pairs) {
  return JSON.stringify(pairs.map(p => p.progressEntries.map(e => e.message?.content ?? null))).length;
}

test('P-4: discarded data omits tool I/O, reasoning text, and toolUseResult', async (t) => {
  const src = await fixturePairs(t);
  const heavy = ['output line 11', 'internal reasoning that only ProgressFull shows', '"limit":100'];
  for (const [source, pairs] of Object.entries(src)) {
    const dropped = structuredClone(pairs);
    const before = progressBodyBytes(pairs);
    dropProgressData(dropped);
    const after = progressBodyBytes(dropped);
    const retained = JSON.stringify(dropped);
    for (const needle of heavy) {
      assert.equal(retained.includes(needle), false, `${source}: "${needle}" must not be retained`);
    }
    assert.equal(retained.includes('toolUseResult'), false, `${source}: toolUseResult must not be retained`);
    assert.ok(after < before * 0.3, `${source}: retained progress content must shrink substantially (${before} -> ${after})`);
    for (const pair of dropped) {
      for (const e of pair.progressEntries) {
        const blocks = Array.isArray(e.message.content) ? e.message.content : [];
        assert.deepEqual(blocks.filter(b => b.type !== 'text'), [], `${source}: only text blocks may remain`);
      }
    }
  }
});

test('P-4b: minimal data required by %Answer%, %Model%, %Tokens%, and %Cwd% remains', async (t) => {
  const src = await fixturePairs(t);
  const dropped = structuredClone(src.claude);
  dropProgressData(dropped);
  const p2 = dropped[1];
  const a4 = p2.progressEntries.find(e => e.type === 'assistant');
  assert.equal(a4.cwd !== undefined && a4.cwd !== '', true, 'cwd remains');
  assert.equal(a4.version, '9.9.9');
  assert.equal(a4.gitBranch, 'feature/x');
  assert.equal(a4.message.model, 'claude-sonnet-5');
  assert.deepEqual(a4.message.content, [{ type: 'text', text: 'Partial thought.' }],
    'only text blocks remain while tool_use blocks are removed');
  const a1 = dropped[0].progressEntries.find(e => e.type === 'assistant');
  assert.equal(a1.message.usage.input_tokens, 10);
  const u2 = dropped[0].progressEntries.find(e => e.type === 'user');
  assert.deepEqual(u2.message.content, []);
});

// ---------------------------------------------------------------------------
// P-4c: the top-level field denylist (Round 2)
// ---------------------------------------------------------------------------

const DEAD_KEYS = [
  'uuid', 'parentUuid', 'timestamp', 'sessionId', 'session_id', 'turnId',
  'requestId', 'promptId', 'userType', 'sourceToolAssistantUUID', 'toolUseResult',
];

test('P-4c: unused top-level ID and timestamp fields are removed', async (t) => {
  const src = await fixturePairs(t);
  for (const [source, pairs] of Object.entries(src)) {
    const beforeKeys = new Set(pairs.flatMap(p => p.progressEntries.flatMap(e => Object.keys(e))));
    for (const key of ['uuid', 'timestamp']) {
      assert.equal(beforeKeys.has(key), true, `${source}: ${key} exists before discarding`);
    }
    const dropped = structuredClone(pairs);
    dropProgressData(dropped);
    for (const pair of dropped) {
      for (const e of pair.progressEntries) {
        for (const key of DEAD_KEYS) {
          assert.equal(key in e, false, `${source}: ${key} must not be retained`);
        }
        assert.equal(typeof e.type, 'string', `${source}: type remains`);
      }
    }
  }
  const cxDropped = structuredClone(src.codex);
  dropProgressData(cxDropped);
  assert.equal(
    cxDropped.some(p => p.progressEntries.some(e => e.isProgressOnly === true)), true,
    'isProgressOnly remains',
  );
});

test('P-4c2: unknown top-level fields not in the denylist are preserved', () => {
  const pair = {
    questionEntry: { type: 'user', uuid: 'u', timestamp: 't', message: { role: 'user', content: 'q' } },
    additionalQuestionEntries: [],
    progressEntries: [{
      type: 'assistant', uuid: 'a', parentUuid: 'u', timestamp: 't', sessionId: 's',
      cwd: '/p', version: '1.0.0', gitBranch: 'main',
      futureFieldAddedLater: 'keep me',
      message: { role: 'assistant', model: 'm', content: [{ type: 'text', text: 'x' }] },
    }],
    finalAssistantEntry: null,
  };
  dropProgressData([pair]);
  const e = pair.progressEntries[0];
  assert.equal(e.futureFieldAddedLater, 'keep me', 'unknown fields are preserved');
  assert.equal(e.cwd, '/p');
  assert.equal(e.version, '1.0.0');
  assert.equal(e.gitBranch, 'main');
  assert.equal('uuid' in e, false);
  assert.equal('sessionId' in e, false);
});

// ---------------------------------------------------------------------------
// P-5: the decision input (does the template need Progress)
// ---------------------------------------------------------------------------

test('P-5: templateUsesProgress distinguishes %Progress% from %ProgressFull%', () => {
  assert.equal(templateUsesProgress('%Question%'), false);
  assert.equal(templateUsesProgress('%Progress%'), true);
  assert.equal(templateUsesProgress('%ProgressFull%'), true);
  assert.equal(templateUsesProgress('%Progress% %ProgressFull%'), true);
  assert.equal(templateUsesProgress('%ProgressBar%'), false);
  assert.equal(progressDataNeeded({ template: TEMPLATES.none }), false);
  assert.equal(progressDataNeeded({ template: TEMPLATES.summary }), true);
  assert.equal(progressDataNeeded({ template: TEMPLATES.full }), true);
});


test('P-5b: switching templates changes the analysis fingerprint and clears the cache', async () => {
  const dir = mkTmp('ccx-progress-cache-');
  try {
    const filePath = path.join(dir, 'a.jsonl');
    fs.writeFileSync(filePath, 'x\n', 'utf-8');
    const st = fs.statSync(filePath);
    const file = {
      filePath,
      root: { dir: '/logs', origin: 'standard', stableRootKey: 'std', recursive: false },
      snapshot: { size: st.size, mtimeMs: st.mtimeMs, dev: st.dev, ino: st.ino },
    };
    const cache = createAnalysisCache();
    const key = cacheKey('claude', file);
    cache.beginCycle();
    cache.useFingerprint(JSON.stringify({ template: TEMPLATES.none }));
    await cache.get(key, file);
    await cache.set(key, file, { outcome: 'used', session: { tag: 'slim' } });
    cache.endCycle();

    cache.beginCycle();
    cache.useFingerprint(JSON.stringify({ template: TEMPLATES.none }));
    assert.equal((await cache.get(key, file)).session.tag, 'slim', 'the same template reuses the entry');
    cache.endCycle();

    cache.beginCycle();
    cache.useFingerprint(JSON.stringify({ template: TEMPLATES.both }));
    assert.equal(await cache.get(key, file), undefined,
      'a slim session is not reused after switching to a template that uses Progress');
    cache.endCycle();
  } finally { rmrf(dir); }
});

// ---------------------------------------------------------------------------
// P-6: switching the template while a watch is running
// ---------------------------------------------------------------------------

const liveWatches = new Set();

function killLiveWatches() {
  for (const c of liveWatches) c.kill('SIGKILL');
  liveWatches.clear();
}

function startWatchUtc(args, home) {
  const child = spawn(process.execPath, [CLI, ...args], { env: childEnv(home), cwd: ROOT });
  liveWatches.add(child);
  const state = { stdout: '', stderr: '' };
  child.stdout.on('data', d => { state.stdout += d; });
  child.stderr.on('data', d => { state.stderr += d; });
  child.on('exit', () => liveWatches.delete(child));
  return { child, state };
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function waitForOutput(ws, fileName, expectedHash, timeoutMs = 40000) {
  const deadline = Date.now() + timeoutMs;
  let last = '(output file does not exist yet)';
  for (;;) {
    try {
      const text = fs.readFileSync(path.join(ws.out, fileName), 'utf-8');
      last = normalize(text, { home: ws.home, project: ws.project });
      if (sha256Text(last) === expectedHash) return last;
    } catch {  }
    if (Date.now() >= deadline) return { timeout: true, last };
    await sleep(150);
  }
}

test('P-6: switching templates during watch always produces correct output', async (t) => {
  const ws = fixtureWorkspace(t);
  clearMd(ws.out);
  useTemplate(ws.out, 'none');
  const w = startWatchUtc([ws.project, '--watch'], ws.home);
  try {
    let r = await waitForOutput(ws, 'ccxlog.md', GOLDEN['none/ccxlog']);
    assert.equal(r.timeout, undefined, `initial output without Progress differs:\n${r.last}\n${w.state.stderr}`);

    useTemplate(ws.out, 'both');
    r = await waitForOutput(ws, 'ccxlog.md', GOLDEN['both/ccxlog']);
    assert.equal(r.timeout, undefined, `output after enabling Progress differs:\n${r.last}\n${w.state.stderr}`);

    useTemplate(ws.out, 'none');
    r = await waitForOutput(ws, 'ccxlog.md', GOLDEN['none/ccxlog']);
    assert.equal(r.timeout, undefined, `output after disabling Progress differs:\n${r.last}\n${w.state.stderr}`);

    useTemplate(ws.out, 'summary');
    r = await waitForOutput(ws, 'ccxlog.md', GOLDEN['summary/ccxlog']);
    assert.equal(r.timeout, undefined, `output after switching to %Progress% alone differs:\n${r.last}\n${w.state.stderr}`);
  } finally {
    w.child.kill('SIGKILL');
  }
});

// ---------------------------------------------------------------------------
// P-7: other uses of the data (slash-command body recovery) keep working
// ---------------------------------------------------------------------------

test('P-7: slash-command content is restored even when the template does not use Progress', (t) => {
  const ws = fixtureWorkspace(t);
  const norm = renderCombination(ws, 'none', 'cc');
  assert.ok(norm.includes(SLASH_FULL_BODY),
    `truncated content was not restored from the tool result:\n${norm}`);
});

test('P-7b: restoration occurs inside buildPairs and is independent of discard order', async (t) => {
  const src = await fixturePairs(t);
  const dropped = structuredClone(src.claude);
  dropProgressData(dropped);
  const restored = dropped[2].additionalQuestionEntries[0].message.content;
  assert.equal(restored, SLASH_FULL_BODY, 'restored content remains on the question side');
});
